-- MySQL Script generated by MySQL Workbench
-- Tue Aug 10 13:15:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Suapocket2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Suapocket2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Suapocket2` DEFAULT CHARACTER SET utf8 ;
USE `Suapocket2` ;

-- -----------------------------------------------------
-- Table `Suapocket2`.`usuario_s`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Suapocket2`.`usuario_s` (
  `usuId` INT(11) NOT NULL AUTO_INCREMENT,
  `usuLogin` VARCHAR(50) NOT NULL,
  `usuPassword` VARCHAR(100) NOT NULL,
  `usuUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `usuEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `usuRemember_token` VARCHAR(100) NOT NULL,
  `usu_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `usu_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuId`),
  UNIQUE INDEX `uniq_login` (`usuLogin` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Suapocket2`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Suapocket2`.`persona` (
  `perId` INT(11) NOT NULL COMMENT 'Nos muetsra el Id de la tabla persona',
  `perDocumento` VARCHAR(20) NOT NULL COMMENT 'Nos muestra el documento de la persona',
  `perNombre` VARCHAR(100) NOT NULL COMMENT 'Nos muestra el nombre de la persona',
  `perApellido` VARCHAR(255) NOT NULL COMMENT 'Nos muestra el apellido de la persona',
  `perEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `perUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `per_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `per_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `usuario_s_usuId` INT(11) NOT NULL,
  PRIMARY KEY (`perId`, `usuario_s_usuId`),
  UNIQUE INDEX `uniq_documento` (`perDocumento` ASC) ,
  INDEX `fk_persona_usuario_s1_idx` (`usuario_s_usuId` ASC) ,
  CONSTRAINT `fk_persona_usuario_s1`
    FOREIGN KEY (`usuario_s_usuId`)
    REFERENCES `Suapocket2`.`usuario_s` (`usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'Esta tabla nos muestra los datos de la persona ';


-- -----------------------------------------------------
-- Table `Suapocket2`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Suapocket2`.`rol` (
  `rolId` INT(11) NOT NULL AUTO_INCREMENT,
  `rolNombre` VARCHAR(32) NOT NULL,
  `rolDescripcion` VARCHAR(255) NOT NULL,
  `rolEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `rolUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `rol_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `rol_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`rolId`),
  UNIQUE INDEX `uniq_nombrerol` (`rolNombre` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Suapocket2`.`usuario_s_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Suapocket2`.`usuario_s_roles` (
  `id_usuario_s` INT(11) NOT NULL,
  `id_rol` INT(11) NOT NULL,
  `estado` TINYINT(1) NOT NULL DEFAULT '1',
  `fechaUserRol` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `obsFechaUserRol` TEXT NULL DEFAULT NULL,
  `usuRolUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario_s`, `id_rol`),
  INDEX `usuario_s_roles_fk_rolidrol` (`id_rol` ASC) ,
  CONSTRAINT `usuario_s_roles_fk_rolidrol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `Suapocket2`.`rol` (`rolId`),
  CONSTRAINT `usuario_s_roles_fk_usuario_sid`
    FOREIGN KEY (`id_usuario_s`)
    REFERENCES `Suapocket2`.`usuario_s` (`usuId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `Suapocket2`.`lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Suapocket2`.`lugar` (
  `idlugar` INT NOT NULL,
  `lugUbicacion` VARCHAR(45) NOT NULL,
  `lugDireccion` VARCHAR(45) NOT NULL,
  `lugCorreo` VARCHAR(45) NOT NULL,
  `lugTelefono` VARCHAR(45) NOT NULL,
  `lugNombre` VARCHAR(45) NOT NULL,
  `lugFecha` VARCHAR(45) NOT NULL,
  `lugImagen` TIMESTAMP NOT NULL,
  `lugUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `lugEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `lug_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `lug_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idlugar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Suapocket2`.`puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Suapocket2`.`puntuacion` (
  `idpuntuacion` INT NOT NULL,
  `punCalificacion_usuario` INT(10) NOT NULL,
  `punComentario_lugar` VARCHAR(45) NOT NULL,
  `punEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `pun_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `pun_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idpuntuacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Suapocket2`.`calificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Suapocket2`.`calificacion` (
  `idcalificacion` INT NOT NULL,
  `puntuacion_idpuntuacion` INT NOT NULL,
  `lugar_idlugar` INT NOT NULL,
  `persona_perId` INT(11) NOT NULL,
  `persona_usuario_s_usuId` INT(11) NOT NULL,
  `calEstado` TINYINT(1) NOT NULL DEFAULT '1',
  `calUsuSesion` VARCHAR(20) NULL DEFAULT NULL,
  `cal_created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `cal_updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`idcalificacion`),
  INDEX `fk_calificacion_puntuacion1_idx` (`puntuacion_idpuntuacion` ASC) ,
  INDEX `fk_calificacion_lugar1_idx` (`lugar_idlugar` ASC) ,
  INDEX `fk_calificacion_persona1_idx` (`persona_perId` ASC, `persona_usuario_s_usuId` ASC) ,
  CONSTRAINT `fk_calificacion_puntuacion1`
    FOREIGN KEY (`puntuacion_idpuntuacion`)
    REFERENCES `Suapocket2`.`puntuacion` (`idpuntuacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_lugar1`
    FOREIGN KEY (`lugar_idlugar`)
    REFERENCES `Suapocket2`.`lugar` (`idlugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificacion_persona1`
    FOREIGN KEY (`persona_perId` , `persona_usuario_s_usuId`)
    REFERENCES `Suapocket2`.`persona` (`perId` , `usuario_s_usuId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `categorialibro` (
  `catLibId` int(11) NOT NULL AUTO_INCREMENT,
  `catLibNombre` varchar(60) COLLATE utf8_unicode_ci NOT NULL,
  `catLibEstado` tinyint(1) NOT NULL DEFAULT '1',
  `catLibObservacion` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`catLibId`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE IF NOT EXISTS `libros` (
  `isbn` int(5) NOT NULL DEFAULT '0',
  `titulo` varchar(236) DEFAULT NULL,
  `autor` varchar(305) DEFAULT NULL,
  `precio` varchar(10) DEFAULT NULL,
  `estado` tinyint(1) NOT NULL DEFAULT '1',
  `categoriaLibro_catLibId` int(11) NOT NULL DEFAULT '1',
  PRIMARY KEY (`isbn`,`categoriaLibro_catLibId`),
  KEY `fk_libros_categoriaLibro1_idx` (`categoriaLibro_catLibId`),
  CONSTRAINT `fk_libros_categoriaLibro1` FOREIGN KEY (`categoriaLibro_catLibId`) REFERENCES `categorialibro` (`catLibId`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
